# Generated by Django 4.2.9 on 2024-01-12 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_song_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
