# Generated by Django 4.2.9 on 2024-01-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_song_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='published_on',
        ),
    ]
