# Generated by Django 4.2.9 on 2024-01-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_song_published_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='bibiography',
            new_name='biography',
        ),
    ]
