# Generated by Django 4.2.9 on 2024-01-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_rename_bibiography_artist_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
    ]
