# Generated by Django 4.2.9 on 2024-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_artist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
